version: '3.4'
volumes:
  my-datavolume:

services:
  db:
    image: mysql
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 4444  
      MYSQL_DATABASE: productshopwm  

    networks:
      - my-network

  newapishop:
    build:
      context: .
      dockerfile: NewAPIShop/Dockerfile
    depends_on:
        - db
    ports:
        - "5082:8080"
    environment:
        - DBHOST=db
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - my-network 


networks:
  my-network:
